parameters:
    pim_catalog.elasticsearch.product_indexer.class: 'Pim\Bundle\CatalogBundle\Elasticsearch\ProductIndexer'
    pim_catalog.elasticsearch.product_model_indexer.class: 'Pim\Bundle\CatalogBundle\Elasticsearch\ProductModelIndexer'

services:
    pim_catalog.elasticsearch.indexer.product:
        class: '%pim_catalog.elasticsearch.product_indexer.class%'
        arguments:
            - '@pim_serializer'
            - '@akeneo_elasticsearch.client.product'
            - '@akeneo_elasticsearch.client.product_and_product_model'
            - 'pim_catalog_product'

    pim_catalog.elasticsearch.indexer.product_model:
        class: '%pim_catalog.elasticsearch.product_model_indexer.class%'
        arguments:
            - '@pim_serializer'
            - '@akeneo_elasticsearch.client.product_and_product_model'
            - 'pim_catalog_product'

    pim_catalog.elasticsearch.indexer.product_model_descendance:
        class: '%pim_catalog.elasticsearch.object_indexer.class%'
        arguments:
            - '@pim_serializer'
            - '@akeneo_elasticsearch.client.product'
            - '@akeneo_elasticsearch.client.product_and_product_model'
            - 'pim_catalog_product'
