pim_enrich_product_model_edit:
    path: /{id}
    methods: [GET, POST]

#pim_enrich_product_model_listcategories:
#    path: /list-categories/product/{id}/parent/{categoryId}
#    defaults: { _controller: pim_enrich.controller.product_model:listCategoriesAction }
#    requirements:
#        id: '[0-9a-f]+'
#        categoryId: \d+

pim_enrich_product_model_rest_get:
    path: /rest/{id}
    defaults: { _controller: pim_enrich.controller.rest.product_model:getAction }
    requirements:
        id: '[0-9a-f]+'
    methods: [GET]

pim_enrich_product_model_rest_create:
    path: /rest
    defaults: { _controller: pim_enrich.controller.rest.product_model:createAction }
    methods: [POST]

pim_enrich_product_model_rest_post:
    path: /rest/{id}
    defaults: { _controller: pim_enrich.controller.rest.product_model:postAction }
    requirements:
        id: '[0-9a-f]+'
    methods: [POST]

pim_enrich_product_model_rest_remove:
    path: /rest/{id}
    defaults: { _controller: pim_enrich.controller.rest.product_model:removeAction, _format: json }
    requirements:
        id: '[0-9a-f]+'
    methods: [DELETE]

pim_enrich_product_model_category_rest_list:
    path: /rest/{id}/categories
    defaults: { _controller: pim_enrich.controller.rest.product_category:listAction }
    requirements:
        id: '[0-9a-f]+'
    methods: [GET]

pim_enrich_product_model_history_rest_get:
    path: /rest/{entityId}/history
    defaults: { _controller: pim_enrich.controller.rest.versioning:getAction, entityType: product }
    requirements:
        entityId: '[0-9a-f]+'
    methods: [GET]

pim_enrich_product_model_remove_attribute_rest:
    path: /rest/{id}/{attributeId}
    defaults: { _controller: pim_enrich.controller.rest.product_model:removeAttributeAction }
    requirements:
        id: '[0-9a-f]+'
        attributeId: '\d+'
    methods: [DELETE]
